name: End-to-end login
on: 
  push:
    paths:
      - cypress/e2e/page_login.cy.js
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run login
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/page_login.cy.js